// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package bootNotificationRequest

import "encoding/json"
import "fmt"
import "reflect"

type BootNotificationRequestJson struct {
	// ChargingStation corresponds to the JSON schema field "chargingStation".
	ChargingStation ChargingStationType `json:"chargingStation" yaml:"chargingStation" mapstructure:"chargingStation"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// Reason corresponds to the JSON schema field "reason".
	Reason BootReasonEnumType `json:"reason" yaml:"reason" mapstructure:"reason"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BootNotificationRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["chargingStation"]; raw != nil && !ok {
		return fmt.Errorf("field chargingStation in BootNotificationRequestJson: required")
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in BootNotificationRequestJson: required")
	}
	type Plain BootNotificationRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BootNotificationRequestJson(plain)
	return nil
}

type BootReasonEnumType string

const BootReasonEnumTypeApplicationReset BootReasonEnumType = "ApplicationReset"
const BootReasonEnumTypeFirmwareUpdate BootReasonEnumType = "FirmwareUpdate"
const BootReasonEnumTypeLocalReset BootReasonEnumType = "LocalReset"
const BootReasonEnumTypePowerUp BootReasonEnumType = "PowerUp"
const BootReasonEnumTypeRemoteReset BootReasonEnumType = "RemoteReset"
const BootReasonEnumTypeScheduledReset BootReasonEnumType = "ScheduledReset"
const BootReasonEnumTypeTriggered BootReasonEnumType = "Triggered"
const BootReasonEnumTypeUnknown BootReasonEnumType = "Unknown"
const BootReasonEnumTypeWatchdog BootReasonEnumType = "Watchdog"

var enumValues_BootReasonEnumType = []interface{}{
	"ApplicationReset",
	"FirmwareUpdate",
	"LocalReset",
	"PowerUp",
	"RemoteReset",
	"ScheduledReset",
	"Triggered",
	"Unknown",
	"Watchdog",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BootReasonEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BootReasonEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BootReasonEnumType, v)
	}
	*j = BootReasonEnumType(v)
	return nil
}

// Charge_ Point
// urn:x-oca:ocpp:uid:2:233122
// The physical system where an Electrical Vehicle (EV) can be charged.
type ChargingStationType struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// This contains the firmware version of the Charging Station.
	//
	//
	FirmwareVersion *string `json:"firmwareVersion,omitempty" yaml:"firmwareVersion,omitempty" mapstructure:"firmwareVersion,omitempty"`

	// Device. Model. CI20_ Text
	// urn:x-oca:ocpp:uid:1:569325
	// Defines the model of the device.
	//
	Model string `json:"model" yaml:"model" mapstructure:"model"`

	// Modem corresponds to the JSON schema field "modem".
	Modem *ModemType `json:"modem,omitempty" yaml:"modem,omitempty" mapstructure:"modem,omitempty"`

	// Device. Serial_ Number. Serial_ Number
	// urn:x-oca:ocpp:uid:1:569324
	// Vendor-specific device identifier.
	//
	SerialNumber *string `json:"serialNumber,omitempty" yaml:"serialNumber,omitempty" mapstructure:"serialNumber,omitempty"`

	// Identifies the vendor (not necessarily in a unique manner).
	//
	VendorName string `json:"vendorName" yaml:"vendorName" mapstructure:"vendorName"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChargingStationType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in ChargingStationType: required")
	}
	if _, ok := raw["vendorName"]; raw != nil && !ok {
		return fmt.Errorf("field vendorName in ChargingStationType: required")
	}
	type Plain ChargingStationType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.FirmwareVersion != nil && len(*plain.FirmwareVersion) > 50 {
		return fmt.Errorf("field %s length: must be <= %d", "firmwareVersion", 50)
	}
	if len(plain.Model) > 20 {
		return fmt.Errorf("field %s length: must be <= %d", "model", 20)
	}
	if plain.SerialNumber != nil && len(*plain.SerialNumber) > 25 {
		return fmt.Errorf("field %s length: must be <= %d", "serialNumber", 25)
	}
	if len(plain.VendorName) > 50 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorName", 50)
	}
	*j = ChargingStationType(plain)
	return nil
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.VendorId) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorId", 255)
	}
	*j = CustomDataType(plain)
	return nil
}

// Wireless_ Communication_ Module
// urn:x-oca:ocpp:uid:2:233306
// Defines parameters required for initiating and maintaining wireless
// communication with other devices.
type ModemType struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// Wireless_ Communication_ Module. ICCID. CI20_ Text
	// urn:x-oca:ocpp:uid:1:569327
	// This contains the ICCID of the modem’s SIM card.
	//
	Iccid *string `json:"iccid,omitempty" yaml:"iccid,omitempty" mapstructure:"iccid,omitempty"`

	// Wireless_ Communication_ Module. IMSI. CI20_ Text
	// urn:x-oca:ocpp:uid:1:569328
	// This contains the IMSI of the modem’s SIM card.
	//
	Imsi *string `json:"imsi,omitempty" yaml:"imsi,omitempty" mapstructure:"imsi,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ModemType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ModemType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Iccid != nil && len(*plain.Iccid) > 20 {
		return fmt.Errorf("field %s length: must be <= %d", "iccid", 20)
	}
	if plain.Imsi != nil && len(*plain.Imsi) > 20 {
		return fmt.Errorf("field %s length: must be <= %d", "imsi", 20)
	}
	*j = ModemType(plain)
	return nil
}
