// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package costUpdatedRequest

import "encoding/json"
import "fmt"

type CostUpdatedRequestJson struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// Current total cost, based on the information known by the CSMS, of the
	// transaction including taxes. In the currency configured with the configuration
	// Variable: [&lt;&lt;configkey-currency, Currency&gt;&gt;]
	//
	//
	TotalCost float64 `json:"totalCost" yaml:"totalCost" mapstructure:"totalCost"`

	// Transaction Id of the transaction the current cost are asked for.
	//
	//
	TransactionId string `json:"transactionId" yaml:"transactionId" mapstructure:"transactionId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CostUpdatedRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["totalCost"]; raw != nil && !ok {
		return fmt.Errorf("field totalCost in CostUpdatedRequestJson: required")
	}
	if _, ok := raw["transactionId"]; raw != nil && !ok {
		return fmt.Errorf("field transactionId in CostUpdatedRequestJson: required")
	}
	type Plain CostUpdatedRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.TransactionId) > 36 {
		return fmt.Errorf("field %s length: must be <= %d", "transactionId", 36)
	}
	*j = CostUpdatedRequestJson(plain)
	return nil
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.VendorId) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorId", 255)
	}
	*j = CustomDataType(plain)
	return nil
}
