// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package getTransactionStatusResponse

import "encoding/json"
import "fmt"

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.VendorId) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorId", 255)
	}
	*j = CustomDataType(plain)
	return nil
}

type GetTransactionStatusResponseJson struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// Whether there are still message to be delivered.
	//
	MessagesInQueue bool `json:"messagesInQueue" yaml:"messagesInQueue" mapstructure:"messagesInQueue"`

	// Whether the transaction is still ongoing.
	//
	OngoingIndicator *bool `json:"ongoingIndicator,omitempty" yaml:"ongoingIndicator,omitempty" mapstructure:"ongoingIndicator,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GetTransactionStatusResponseJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["messagesInQueue"]; raw != nil && !ok {
		return fmt.Errorf("field messagesInQueue in GetTransactionStatusResponseJson: required")
	}
	type Plain GetTransactionStatusResponseJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GetTransactionStatusResponseJson(plain)
	return nil
}
