// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package setMonitoringBaseRequest

import "encoding/json"
import "fmt"
import "reflect"

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.VendorId) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorId", 255)
	}
	*j = CustomDataType(plain)
	return nil
}

type MonitoringBaseEnumType string

const MonitoringBaseEnumTypeAll MonitoringBaseEnumType = "All"
const MonitoringBaseEnumTypeFactoryDefault MonitoringBaseEnumType = "FactoryDefault"
const MonitoringBaseEnumTypeHardWiredOnly MonitoringBaseEnumType = "HardWiredOnly"

var enumValues_MonitoringBaseEnumType = []interface{}{
	"All",
	"FactoryDefault",
	"HardWiredOnly",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MonitoringBaseEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MonitoringBaseEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MonitoringBaseEnumType, v)
	}
	*j = MonitoringBaseEnumType(v)
	return nil
}

type SetMonitoringBaseRequestJson struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// MonitoringBase corresponds to the JSON schema field "monitoringBase".
	MonitoringBase MonitoringBaseEnumType `json:"monitoringBase" yaml:"monitoringBase" mapstructure:"monitoringBase"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetMonitoringBaseRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["monitoringBase"]; raw != nil && !ok {
		return fmt.Errorf("field monitoringBase in SetMonitoringBaseRequestJson: required")
	}
	type Plain SetMonitoringBaseRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetMonitoringBaseRequestJson(plain)
	return nil
}
