// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package clearedChargingLimitRequest

import "encoding/json"
import "fmt"
import "reflect"

type ChargingLimitSourceEnumType string

const ChargingLimitSourceEnumTypeCSO ChargingLimitSourceEnumType = "CSO"
const ChargingLimitSourceEnumTypeEMS ChargingLimitSourceEnumType = "EMS"
const ChargingLimitSourceEnumTypeOther ChargingLimitSourceEnumType = "Other"
const ChargingLimitSourceEnumTypeSO ChargingLimitSourceEnumType = "SO"

var enumValues_ChargingLimitSourceEnumType = []interface{}{
	"EMS",
	"Other",
	"SO",
	"CSO",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChargingLimitSourceEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ChargingLimitSourceEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ChargingLimitSourceEnumType, v)
	}
	*j = ChargingLimitSourceEnumType(v)
	return nil
}

type ClearedChargingLimitRequestJson struct {
	// ChargingLimitSource corresponds to the JSON schema field "chargingLimitSource".
	ChargingLimitSource ChargingLimitSourceEnumType `json:"chargingLimitSource" yaml:"chargingLimitSource" mapstructure:"chargingLimitSource"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// EVSE Identifier.
	//
	EvseId *int `json:"evseId,omitempty" yaml:"evseId,omitempty" mapstructure:"evseId,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClearedChargingLimitRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["chargingLimitSource"]; raw != nil && !ok {
		return fmt.Errorf("field chargingLimitSource in ClearedChargingLimitRequestJson: required")
	}
	type Plain ClearedChargingLimitRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ClearedChargingLimitRequestJson(plain)
	return nil
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.VendorId) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorId", 255)
	}
	*j = CustomDataType(plain)
	return nil
}
