// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package statusNotificationRequest

import "encoding/json"
import "fmt"
import "reflect"
import "time"

type ConnectorStatusEnumType string

const ConnectorStatusEnumTypeAvailable ConnectorStatusEnumType = "Available"
const ConnectorStatusEnumTypeFaulted ConnectorStatusEnumType = "Faulted"
const ConnectorStatusEnumTypeOccupied ConnectorStatusEnumType = "Occupied"
const ConnectorStatusEnumTypeReserved ConnectorStatusEnumType = "Reserved"
const ConnectorStatusEnumTypeUnavailable ConnectorStatusEnumType = "Unavailable"

var enumValues_ConnectorStatusEnumType = []interface{}{
	"Available",
	"Occupied",
	"Reserved",
	"Unavailable",
	"Faulted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorStatusEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ConnectorStatusEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ConnectorStatusEnumType, v)
	}
	*j = ConnectorStatusEnumType(v)
	return nil
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.VendorId) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorId", 255)
	}
	*j = CustomDataType(plain)
	return nil
}

type StatusNotificationRequestJson struct {
	// The id of the connector within the EVSE for which the status is reported.
	//
	ConnectorId int `json:"connectorId" yaml:"connectorId" mapstructure:"connectorId"`

	// ConnectorStatus corresponds to the JSON schema field "connectorStatus".
	ConnectorStatus ConnectorStatusEnumType `json:"connectorStatus" yaml:"connectorStatus" mapstructure:"connectorStatus"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`

	// The id of the EVSE to which the connector belongs for which the the status is
	// reported.
	//
	EvseId int `json:"evseId" yaml:"evseId" mapstructure:"evseId"`

	// The time for which the status is reported. If absent time of receipt of the
	// message will be assumed.
	//
	Timestamp time.Time `json:"timestamp" yaml:"timestamp" mapstructure:"timestamp"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StatusNotificationRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connectorId"]; raw != nil && !ok {
		return fmt.Errorf("field connectorId in StatusNotificationRequestJson: required")
	}
	if _, ok := raw["connectorStatus"]; raw != nil && !ok {
		return fmt.Errorf("field connectorStatus in StatusNotificationRequestJson: required")
	}
	if _, ok := raw["evseId"]; raw != nil && !ok {
		return fmt.Errorf("field evseId in StatusNotificationRequestJson: required")
	}
	if _, ok := raw["timestamp"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp in StatusNotificationRequestJson: required")
	}
	type Plain StatusNotificationRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = StatusNotificationRequestJson(plain)
	return nil
}
