// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package signCertificateRequest

import "encoding/json"
import "fmt"
import "reflect"

type CertificateSigningUseEnumType string

const CertificateSigningUseEnumTypeChargingStationCertificate CertificateSigningUseEnumType = "ChargingStationCertificate"
const CertificateSigningUseEnumTypeV2GCertificate CertificateSigningUseEnumType = "V2GCertificate"

var enumValues_CertificateSigningUseEnumType = []interface{}{
	"ChargingStationCertificate",
	"V2GCertificate",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CertificateSigningUseEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CertificateSigningUseEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CertificateSigningUseEnumType, v)
	}
	*j = CertificateSigningUseEnumType(v)
	return nil
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.VendorId) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "vendorId", 255)
	}
	*j = CustomDataType(plain)
	return nil
}

type SignCertificateRequestJson struct {
	// CertificateType corresponds to the JSON schema field "certificateType".
	CertificateType *CertificateSigningUseEnumType `json:"certificateType,omitempty" yaml:"certificateType,omitempty" mapstructure:"certificateType,omitempty"`

	// The Charging Station SHALL send the public key in form of a Certificate Signing
	// Request (CSR) as described in RFC 2986 [22] and then PEM encoded, using the
	// &lt;&lt;signcertificaterequest,SignCertificateRequest&gt;&gt; message.
	//
	Csr string `json:"csr" yaml:"csr" mapstructure:"csr"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty" mapstructure:"customData,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SignCertificateRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["csr"]; raw != nil && !ok {
		return fmt.Errorf("field csr in SignCertificateRequestJson: required")
	}
	type Plain SignCertificateRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.Csr) > 5500 {
		return fmt.Errorf("field %s length: must be <= %d", "csr", 5500)
	}
	*j = SignCertificateRequestJson(plain)
	return nil
}
